---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

bases:
  - ../../apps/nsmgr
  - ../../apps/forwarder-vpp
  - ../../apps/registry-k8s

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: forwarder-vpp
    path: patch-forwarder-vpp.yaml
